import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const references = path.join(root, 'skills/dsh-ppt/references');
const definitions = [];
const semantics = {};
const previews = {};
const previewFiles = {};

for (const category of await readdir(references, { withFileTypes: true })) {
  if (!category.isDirectory()) continue;
  for (const entry of await readdir(path.join(references, category.name), { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const directory = `${category.name}/${entry.name}`;
    const spec = JSON.parse(await readFile(path.join(references, directory, 'metadata.json'), 'utf8'));
    const { definition } = spec;
    assert.equal(definition.referenceDirectory, directory, 'Template path must match its metadata');
    assert(!Object.hasOwn(previews, definition.id), `Duplicate template: ${definition.id}`);
    definitions.push(definition);
    semantics[definition.id] = spec.semantics;
    previews[definition.id] = [];
    for (const page of definition.previewSlides) {
      assert(Number.isInteger(page) && page > 0 && page <= definition.referencePageCount, 'Invalid preview page');
      const relative = `${directory}/pages/${String(page).padStart(2, '0')}.jpg`;
      const bytes = await readFile(path.join(references, relative));
      const hash = createHash('sha256').update(bytes).digest('hex');
      previewFiles[hash] = relative;
      previews[definition.id].push(`/dsh-ppt/previews/${hash}.jpg`);
    }
  }
}
assert(definitions.length > 0, 'No PPT templates found');
definitions.sort((a, b) => a.id.localeCompare(b.id));

const marker = '/* GENERATED_PPT_PREVIEWS */ {}';
const client = await readFile(path.join(root, 'src/client.js'), 'utf8');
assert.equal(client.split(marker).length, 2, 'Expected one preview insertion marker');
await writeFile(path.join(root, 'lib/client.js'), client.replace(marker, JSON.stringify(previews)));
await writeFile(path.join(root, 'lib/catalog.js'),
  `// Generated by scripts/build.mjs from bundled template metadata.\nexport const definitions = ${JSON.stringify(definitions)};\nexport const semantics = ${JSON.stringify(semantics)};\n`);
await writeFile(path.join(root, 'lib/preview-manifest.js'),
  `// Only bundled, content-addressed template previews may be served.\nexport const previewFiles = ${JSON.stringify(previewFiles)};\n`);
console.error(`Built dsh-ppt: ${definitions.length} templates, ${Object.keys(previewFiles).length} preview images.`);
